github: [EndyKaufman]
patreon: EndyKaufman
# open_collective: # Replace with a single Open Collective username
ko_fi: endykaufman
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: EndyKaufman
issuehunt: endykaufman
# otechie: # Replace with a single Otechie username
# lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
# custom: # [https://yoomoney.ru/to/41001220209977]
