version: "3"
networks:
  kaufman-network:
    ipam:
      config:
        - subnet: "172.120.0.0/16"

services:
  kaufman-bot:
    image: "kaufman/bot:local"
    container_name: "kaufman-bot-service"
    environment:
      - PORT=5000
      - AUTOSTART=${AUTOSTART}
      - BOT_LOCALE=${BOT_LOCALE}
      - BOT_NAME_ALIASES=${BOT_NAME_ALIASES}
      - GOOGLE_APIS_HABR_SEARCH_QUERY_PREFIX=${GOOGLE_APIS_HABR_SEARCH_QUERY_PREFIX}
      - GOOGLE_APIS_HABR_SEARCH_SPY_WORDS=${GOOGLE_APIS_HABR_SEARCH_SPY_WORDS}
      - GOOGLE_APIS_HABR_WHAT_CAN_I_DO_EN=${GOOGLE_APIS_HABR_WHAT_CAN_I_DO_EN}
      - GOOGLE_APIS_HABR_WHAT_CAN_I_DO_RU=${GOOGLE_APIS_HABR_WHAT_CAN_I_DO_RU}
      - SCRAPER_BASHORG_CONTENT_LENGTH=${SCRAPER_BASHORG_CONTENT_LENGTH}
      - SCRAPER_BASHORG_CONTENT_SELECTOR=${SCRAPER_BASHORG_CONTENT_SELECTOR}
      - SCRAPER_BASHORG_SPY_WORDS=${SCRAPER_BASHORG_SPY_WORDS}
      - SCRAPER_BASHORG_TIMEOUT=${SCRAPER_BASHORG_TIMEOUT}
      - SCRAPER_BASHORG_URI=${SCRAPER_BASHORG_URI}
      - SCRAPER_BASHORG_WHAT_CAN_I_DO_EN=${SCRAPER_BASHORG_WHAT_CAN_I_DO_EN}
      - SCRAPER_BASHORG_WHAT_CAN_I_DO_RU=${SCRAPER_BASHORG_WHAT_CAN_I_DO_RU}
      - SCRAPER_FORISMATIC_CONTENT_LENGTH=${SCRAPER_FORISMATIC_CONTENT_LENGTH}
      - SCRAPER_FORISMATIC_CONTENT_SELECTOR=${SCRAPER_FORISMATIC_CONTENT_SELECTOR}
      - SCRAPER_FORISMATIC_SPY_WORDS=${SCRAPER_FORISMATIC_SPY_WORDS}
      - SCRAPER_FORISMATIC_TIMEOUT=${SCRAPER_FORISMATIC_TIMEOUT}
      - SCRAPER_FORISMATIC_URI=${SCRAPER_FORISMATIC_URI}
      - SCRAPER_FORISMATIC_WHAT_CAN_I_DO_EN=${SCRAPER_FORISMATIC_WHAT_CAN_I_DO_EN}
      - SCRAPER_FORISMATIC_WHAT_CAN_I_DO_RU=${SCRAPER_FORISMATIC_WHAT_CAN_I_DO_RU}
      - SCRAPER_PING_CONTENT_LENGTH=${SCRAPER_PING_CONTENT_LENGTH}
      - SCRAPER_PING_CONTENT_SELECTOR=${SCRAPER_PING_CONTENT_SELECTOR}
      - SCRAPER_PING_SPY_WORDS=${SCRAPER_PING_SPY_WORDS}
      - SCRAPER_PING_TIMEOUT=${SCRAPER_PING_TIMEOUT}
      - SCRAPER_PING_URI=${SCRAPER_PING_URI}
      - SCRAPER_PING_WHAT_CAN_I_DO_EN=${SCRAPER_PING_WHAT_CAN_I_DO_EN}
      - SCRAPER_PING_WHAT_CAN_I_DO_RU=${SCRAPER_PING_WHAT_CAN_I_DO_RU}
      - TELEGRAM_BOT_LOCALE=${TELEGRAM_BOT_LOCALE}
      - TELEGRAM_BOT_NAME_ALIASES=${TELEGRAM_BOT_NAME_ALIASES}
      - TELEGRAM_HOOK_URL=${TELEGRAM_HOOK_URL}
      - WIKIPEDIA_CONTENT_LENGTH=${WIKIPEDIA_CONTENT_LENGTH}
      - WIKIPEDIA_SPY_WORDS=${WIKIPEDIA_SPY_WORDS}
      - APIAI_CLIENT_ACCESS_TOKEN=${APIAI_CLIENT_ACCESS_TOKEN}
      - BOT_ADMIN_TELEGRAM_ID=${BOT_ADMIN_TELEGRAM_ID}
      - GOOGLE_APIS_API_KEY=${GOOGLE_APIS_API_KEY}
      - GOOGLE_APIS_HABR_CUSTOM_SEARCH_ENGINE_ID=${GOOGLE_APIS_HABR_CUSTOM_SEARCH_ENGINE_ID}
      - MICROSOFT_APP_ID=${MICROSOFT_APP_ID}
      - MICROSOFT_APP_PASSWORD=${MICROSOFT_APP_PASSWORD}
      - ROLLBAR_POST_SERVER_ITEM_ACCESS_TOKEN=${ROLLBAR_POST_SERVER_ITEM_ACCESS_TOKEN}
      - ROLLBAR_SERVER_ACCESS_TOKEN=${ROLLBAR_SERVER_ACCESS_TOKEN}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    build:
      context: ../../
      dockerfile: ./docker/__Dockerfile/Dockerfile.kaufman-bot
    # network_mode: host
    networks:
      - kaufman-network
    # extra_hosts:
    #   - "host.docker.internal:172.11.0.1"
    ports:
      - "5000:5000"
    tty: true
