FROM node:alpine as builder
LABEL maintainer="admin@site15.ru"
WORKDIR /usr/src/app
RUN yarn install --link-duplicates --non-interactive
RUN rm -rf ./node_modules/typescript
RUN rm -rf ./env
RUN rm -rf ./docker
RUN rm -rf ./k8s
RUN yarn autoclean --force
COPY . .

# ---

FROM node:alpine
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/ /usr/src/app/
EXPOSE 5000
STOPSIGNAL SIGINT
CMD ["node", "./dist/bin/app.js","-s"]